### ISSUE TITLE
Middle wrong in binary search ?

### ISSUE THREAD

**Issue by faysou** [Skarlso/grokking-algorithms#1]
https://github.com/Skarlso/grokking-algorithms/blob/main/chapter01/binary_search.go

I think the computation of middle in the binary search lacks a divided by 2.

**Comment by Skarlso** [comment]
Oh well done! Good spot! Thank you! :))

**Comment by Skarlso** [comment]
Later on the other binary search implementations do have that. I guess I just missed this one somehow. :) Thank you very much for pointing it out! :)

**Comment by faysou** [comment]
You're welcome, yes I noticed it was ok in other files.
