### ISSUE TITLE
Need corrections in the grid - Chapter9 - exercise.md

### ISSUE THREAD

**Issue by niel-biswas** [Skarlso/grokking-algorithms#4]
I think the below values should be updated:

1. (3,3): 12 (f,b)
2. (4,3): 12 (f,b)
3. (5,4): 18 (c,f,b)
4. (3,6): 22 (w,b,f)
5. (4,6): 22 (w,b,f)

![image](https://github.com/Skarlso/grokking-algorithms/assets/69772908/f5396f3e-4a0f-45d8-ad66-89c1450a37c5)

However, the final answer 25 (w,f,c) is correct since the cells dependent for calculations are derived correctly.

**Comment by Skarlso** [comment]
Hello! :)

Thanks! Any explanation why you think those values are good?

**Comment by niel-biswas** [comment]
Sure. Following the author's point, for a typical knapsack problem, the formula below applies to each cell.

```go
if item.Weight > j {
				cell[i][j] = cell[i-1][j]
			} else {
				cell[i][j] = max(cell[i-1][j], (item.Value + cell[i-1][j-item.Weight]))
			}
```

I just thought to recalculate each cell value on plain pen & paper and found these differences. If you are okay with this, Can I raise a PR?
